### ISSUE TITLE
How to enable compression support?

### ISSUE THREAD

**Issue by dzenanz** [xtensor-stack/xtensor-zarr#56]
```c++
  xt::xzarr_file_system_store store(this->m_FileName); // version 2 file
  auto h = xt::get_zarr_hierarchy(store);
  //std::cout << "h.get_nodes " << h.get_nodes().dump(); // attempts to read non-existent file
  //std::cout << "h.get_children " << h.get_children("/").dump(); // attempts to read non-existent file
  std::cout << "h.get_array " << h.get_array("spectra"); // Unkown compressor type: blosc
```
Stepping through the code using debugger, I noticed that `instance().m_builders` only contains one entry: `binary`. As I had to specify the paths to `zlib` and `blosc`, I went back to CMake configurations, and noticed that `xtensor-io` has a few `have` settings so I enabled `HAVE_Blosc`, `HAVE_GDAL` and `HAVE_ZLIB`. After an incremental build of `xtensor-io` and `xtensor-zarr`, now  `instance().m_builders` contains no entries. What am I doing wrong?

**Comment by davidbrochart** [comment]
You need to register the compressor first, like so:
https://github.com/xtensor-stack/xtensor-zarr/blob/90f0acfbf74a4e3664b0861920409b6143600d67/test/test_gcs.cpp#L22.

**Comment by dzenanz** [comment]
When I add that, I run into a link error: `itkIOOMEZarrNGFF-5.3.lib(itkOMEZarrNGFFImageIO.obj) : error LNK2019: unresolved external symbol "void __cdecl xt::xzarr_register_compressor<class xt::xzarr_file_system_store,struct xt::xio_blosc_config>(void)" (??$xzarr_register_compressor@Vxzarr_file_system_store@xt@@Uxio_blosc_config@2@@xt@@YAXXZ) referenced in function "protected: __cdecl itk::OMEZarrNGFFImageIO::OMEZarrNGFFImageIO(void)" (??0OMEZarrNGFFImageIO@itk@@IEAA@XZ)`. This should not happen, as that procedure is templated. Do you have any suggestion? If it helps, my current code is [here](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/496c5be7a6fd6f5221c190a251bbcdc35fe3bdd0).

**Comment by davidbrochart** [comment]
I don't know, maybe @JohanMabille has some ideas?

**Comment by JohanMabille** [comment]
We have some precompiled instantiations of `xzarr_register_compressor`, maybe they prevent the ocmpiler from instantiating a new one?

Can you try adding this in your code before calling the register function (do not forget the `declspec(dllexport/dllimport)` if you need to use this instantitation in another library):

```cpp
namespace xt
{
    template void xzarr_register_compressor<xzarr_file_system_store, xio_blosc_config>();
}
```

**Comment by dzenanz** [comment]
Yes, that did it. Perhaps it should be added to documentation? See #57.

**Comment by JohanMabille** [comment]
@dzenanz yes definitely. Would you like to open a PR?

**Comment by dzenanz** [comment]
I just added a new commit to #54.
