### ISSUE TITLE
Parallel I/O

### ISSUE THREAD

**Issue by aosterthun** [xtensor-stack/xtensor-zarr#64]
Hi,

I was wondering if the I/O is parallelized. I couldn't find anything concrete regarding this topic in the documentation.

**Comment by davidbrochart** [comment]
Hi @aosterthun, I/O is not parallelized. Actually, the "scheduler" is currently sequential, so parallel I/O would not help. More sophisticated schedulers, similar to what [Dask](https://github.com/dask/dask) does, would be a great addition.

**Comment by aosterthun** [comment]
Ok good to know. Thanks for the quick response.
